# Generated by Django 4.2.13 on 2024-11-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="movie",
            new_name="book",
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="book/images/", verbose_name="书籍封面"),
        ),
    ]
